###
# Libraries and samples for analysis: please update all fields. Separate multiple samples with commas.
######################################################
library:
  A98254A:  
    sample: SA535X4XB09109
    pdxid: X0011_2362
    mainsite: Metastasis
    origin: Left_Axillary
    grouping: A98254A
  A118855A:
    sample: SA535X4XB05985
    pdxid: X0011_2364
    mainsite: Metastasis
    origin: Axillary
    grouping: A118855A
  A98244A:  
    sample: SA535X4XB09109
    pdxid: X0011_2362
    mainsite: Metastasis
    origin: Left_Axillary
    grouping: A98244A

    
  # Return it back
  A98296A_05662:
    sample: SA535X4XB05662
    pdxid: X0011_2363
    mainsite: Metastasis
    origin: Tumor_Recur
    grouping: A98296A_05662
  A98296A_05667:
    sample: SA535X4XB05667
    pdxid: X0011_2363
    mainsite: Metastasis
    origin: Axillary
    grouping: A98296A_05667

# Snakemake params: Please update all fields
############################
download_data: False
filter_data: False
merge_data: False
convert_state_format: True
state_to_binary: True
corrupt_tree_features: True
corrupt_tree_straightened_features: True
corrupt_tree_sync_cnv_features: True
get_sync_cnv_features: True
corrupt_filter: True
outlier_threshold: '0.9'
thrs_map_reads: '10000'


# Snakemake params: samples for clonealign
############################
#sample: raw_segments
max_iteration: 150
clone_probs: '0.45'
execute_clonealign: True
clone_assignment: False
visualize_clonealign: True

sample:
  - SA535X4XB02498
  - SA535X4XB05391
  - SA535X4XB05462

# Corrupt tree params; Adjust as necessary
############################################
saveStandardStreams: 'false'
recordGitInfo: 'false'
managedExecutionFolder: 'false'
neighborhoodSize: '2'
lowerFraction: '0.01'   #0.005
globalParameterization: 'false'
fprBound: '0.01'  # default 0.1 tested, 0.01
fnrBound: '0.5'
engine: 'PT'
initialization : 'FORWARD'
ladder: 'Polynomial'
nScans: '2000'  # default 10000, can try different values 2000, 5000
nPassesPerScan: '1'
nChains: '3'  # default 10
nThreads: 'Fixed'
nThreadsNumber: '16'  # default 20
postprocessor: 'DefaultPostProcessor'
logisticTransform: 'false'
size_shape: 'width'
size_val: '300'
thinningPeriod: '10'
phylo: 'file'
read_only_matrix: 'ReadOnlyCLMatrix'

# Tree cut params: Adjust as necessary
############################################
minimum_fraction: "0.02"
maximum_fraction: "0.55"  #default 0.45, vary in [0.1, 0.9]
resolution_graph_cut: "0.01"  # in case we use Leiden graph cut algo, check again


# Trajectory params
############################################
datatag: "SA535"
ebola_trajectory: True
graph_cut_tree_viz: False
dream_tree: False
prevalence_plot: True


# Directory parameters: Please update all fields
############################################
project_dir: '/home/htran/Projects/hakwoo_project/corrupt_tree'
project_10x_dir: '/home/htran/Projects/hakwoo_project/rscript'
compiled_code_dir: '/home/htran/Projects/hakwoo_project/corrupt_code/bin'
nowellpack_dir: '/home/htran/storage/install_software/nowellpack/build/install/nowellpack/bin'
nextflow_dir: '/home/htran/storage/install_software/corrupt-nextflow'
download_dir: '/home/htran/storage/datasets/hakwoo_metastasis/SA535'
results_dir: '/home/htran/storage/datasets/metastasis_results/SA535_new_encoding/SA535_wholedata_v2'
results_10x_dir: '/home/htran/storage/datasets/metastasis_results/rnaseq_SA535'
results_pseudobk_dir: '/home/htran/storage/datasets/metastasis_results/pseudobk_SA535'
